### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by manvirvirk** [ShawDa/unet-rgb#10]
Traceback (most recent call last):
  File "unet.py", line 137, in <module>
    model = myunet.get_unet()
  File "unet.py", line 59, in get_unet
    merge6 = merge([drop4, up6], mode='concat', concat_axis=3)
TypeError: 'module' object is not callable
can anyone help?

**Comment by ShawDa** [comment]
Check your Python and Keras version, also your import msg on top if the py file.

**Comment by anomoto** [comment]
I have solved the same problem replacing "mergeXX = merge([YYY,ZZZ], mode = 'concat', concat_axis = N)"
with "mergeXX= concatenate([YYY,ZZZ],axis=N)" via [this](https://github.com/zhixuhao/unet/issues/77#issuecomment-431285283)

**Comment by dehai-bai** [comment]
Try to add 'from keras.layers import merge' in unet.py file.
