### ISSUE TITLE
No such file or directory: './npydata/imgs_train.npy'

### ISSUE THREAD

**Issue by WangZhi-wz** [ShawDa/unet-rgb#14]
请问我用自己的数据集运行data.py
报的这个错误是什么意思呢
Creating training images...
D:\anaconda\envs\tensorflow\lib\site-packages\keras_preprocessing\image\utils.py:107: UserWarning: grayscale is deprecated. Please use color_mode = "grayscale"
  warnings.warn('grayscale is deprecated. Please use '
Done: 0/900 images
Done: 100/900 images
Done: 200/900 images
Done: 300/900 images
Done: 400/900 images
Done: 500/900 images
Done: 600/900 images
Done: 700/900 images
Done: 800/900 images
Traceback (most recent call last):
  File "D:/Paper_project/unet-rgb-master/data.py", line 93, in <module>
    mydata.create_train_data()
  File "D:/Paper_project/unet-rgb-master/data.py", line 41, in create_train_data
    np.save(self.npy_path + '/imgs_train.npy', imgdatas)
  File "<__array_function__ internals>", line 6, in save
  File "D:\anaconda\envs\tensorflow\lib\site-packages\numpy\lib\npyio.py", line 524, in save
    file_ctx = open(file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: './npydata/imgs_train.npy'
loading done

Process finished with exit code 1

**Comment by WangZhi-wz** [comment]
知道了，我需要自己创建好npydata等文件夹
我以为会自己创建文件夹的。。。
